In [6]:
import sys
import talib
sys.path.append(r'D:\Workspace\Programmer\nsepython')

In [7]:
import nsepython as nse

In [8]:
symbol = "TCS"
series = "EQ"
start_date = "7-02-2024"
end_date ="15-02-2025"

In [9]:
hcl = nse.equity_history(symbol,series,start_date,end_date)
hcl.sort_values(by='TIMESTAMP', ascending = True, inplace = True)

In [10]:
hcl

,_id,CH_SYMBOL,CH_SERIES,CH_MARKET_TYPE,CH_TIMESTAMP,TIMESTAMP,CH_TRADE_HIGH_PRICE,CH_TRADE_LOW_PRICE,CH_OPENING_PRICE,CH_CLOSING_PRICE,...,CH_52WEEK_LOW_PRICE,CH_TOTAL_TRADES,CH_ISIN,createdAt,updatedAt,__v,SLBMH_TOT_VAL,VWAP,mTIMESTAMP,CA
235,65c370ff06bf92bcaaeaae4d,TCS,EQ,N,2024-02-07,2024-02-06T18:30:00.000Z,4155.00,4073.95,4153.00,4083.40,...,3070.25,177689,INE467B01029,2024-02-07T12:01:03.692Z,2024-02-07T12:01:03.692Z,0,None,4115.33,07-Feb-2024,NaN
236,65c4c27f57e8417d003e2b1d,TCS,EQ,N,2024-02-08,2024-02-07T18:30:00.000Z,4158.00,4086.05,4090.00,4134.10,...,3070.25,212471,INE467B01029,2024-02-08T12:01:03.986Z,2024-02-08T12:01:03.986Z,0,None,4122.74,08-Feb-2024,NaN
237,65c61400b16d2a11203bd0cd,TCS,EQ,N,2024-02-09,2024-02-08T18:30:00.000Z,4184.75,4100.00,4136.55,4133.70,...,3070.25,204415,INE467B01029,2024-02-09T12:01:04.013Z,2024-02-09T12:01:04.013Z,0,None,4135.50,09-Feb-2024,NaN
238,65ca087f1de075c7ebe81602,TCS,EQ,N,2024-02-12,2024-02-11T18:30:00.000Z,4159.60,4105.55,4130.00,4120.70,...,3070.25,110339,INE467B01029,2024-02-12T12:01:03.885Z,2024-02-12T12:01:03.885Z,0,None,4128.10,12-Feb-2024,NaN
239,65cb59ff3328eca8adc58a51,TCS,EQ,N,2024-02-13,2024-02-12T18:30:00.000Z,4170.00,4081.50,4125.45,4149.50,...,3070.25,140800,INE467B01029,2024-02-13T12:01:03.638Z,2024-02-13T12:01:03.638Z,0,None,4130.03,13-Feb-2024,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,67a9ea8015b873eaf995575c,TCS,EQ,N,2025-02-10,2025-02-09T18:30:00.000Z,4052.00,4014.35,4040.00,4036.95,...,3591.50,133697,INE467B01029,2025-02-10T12:01:04.988Z,2025-02-10T12:01:04.988Z,0,None,4035.26,10-Feb-2025,NaN
7,67ab3c0085f54dccaefe1feb,TCS,EQ,N,2025-02-11,2025-02-10T18:30:00.000Z,4040.00,3955.00,4018.40,3963.55,...,3591.50,121478,INE467B01029,2025-02-11T12:01:04.753Z,2025-02-11T12:01:04.753Z,0,None,3989.58,11-Feb-2025,NaN
8,67ac8d80b6348ac3a2cedb9e,TCS,EQ,N,2025-02-12,2025-02-11T18:30:00.000Z,4021.75,3940.15,3971.10,3950.15,...,3591.50,128576,INE467B01029,2025-02-12T12:01:04.423Z,2025-02-12T12:01:04.423Z,0,None,3978.32,12-Feb-2025,NaN
9,67addf0066a44f12b734c888,TCS,EQ,N,2025-02-13,2025-02-12T18:30:00.000Z,3984.45,3902.25,3968.00,3910.15,...,3591.50,163030,INE467B01029,2025-02-13T12:01:04.267Z,2025-02-13T12:01:04.267Z,0,None,3930.80,13-Feb-2025,NaN
10,67af30808e0d781dcf0334ad,TCS,EQ,N,2025-02-14,2025-02-13T18:30:00.000Z,3948.00,3900.00,3925.00,3934.85,...,3591.50,163805,INE467B01029,2025-02-14T12:01:04.438Z,2025-02-14T12:01:04.438Z,0,None,3921.57,14-Feb-2025,NaN

In [11]:
op = hcl['CH_OPENING_PRICE'].astype(float)
hi = hcl['CH_TRADE_HIGH_PRICE'].astype(float)
lo = hcl['CH_TRADE_LOW_PRICE'].astype(float)
cl = hcl['CH_CLOSING_PRICE'].astype(float)

op

235    4153.00
236    4090.00
237    4136.55
238    4130.00
239    4125.45
        ...
6      4040.00
7      4018.40
8      3971.10
9      3968.00
10     3925.00
Name: CH_OPENING_PRICE, Length: 264, dtype: float64

In [12]:
hcl['DOJI'] = talib.CDLDOJI(op, hi, lo, cl)
hcl['Engulfing'] = talib.CDLENGULFING(op, hi, lo, cl)
hcl['HAMMER'] = talib.CDLHAMMER(op, hi, lo, cl)
hcl['HANGINGMAN'] = talib.CDLHANGINGMAN(op, hi, lo, cl)
hcl['HARAMI'] = talib.CDLHARAMI(op, hi, lo, cl)
hcl['MORNINGSTAR'] = talib.CDLMORNINGSTAR(op, hi, lo, cl)

In [13]:
hcl

,_id,CH_SYMBOL,CH_SERIES,CH_MARKET_TYPE,CH_TIMESTAMP,TIMESTAMP,CH_TRADE_HIGH_PRICE,CH_TRADE_LOW_PRICE,CH_OPENING_PRICE,CH_CLOSING_PRICE,...,SLBMH_TOT_VAL,VWAP,mTIMESTAMP,CA,DOJI,Engulfing,HAMMER,HANGINGMAN,HARAMI,MORNINGSTAR
235,65c370ff06bf92bcaaeaae4d,TCS,EQ,N,2024-02-07,2024-02-06T18:30:00.000Z,4155.00,4073.95,4153.00,4083.40,...,None,4115.33,07-Feb-2024,NaN,0,0,0,0,0,0
236,65c4c27f57e8417d003e2b1d,TCS,EQ,N,2024-02-08,2024-02-07T18:30:00.000Z,4158.00,4086.05,4090.00,4134.10,...,None,4122.74,08-Feb-2024,NaN,0,0,0,0,0,0
237,65c61400b16d2a11203bd0cd,TCS,EQ,N,2024-02-09,2024-02-08T18:30:00.000Z,4184.75,4100.00,4136.55,4133.70,...,None,4135.50,09-Feb-2024,NaN,0,0,0,0,0,0
238,65ca087f1de075c7ebe81602,TCS,EQ,N,2024-02-12,2024-02-11T18:30:00.000Z,4159.60,4105.55,4130.00,4120.70,...,None,4128.10,12-Feb-2024,NaN,0,0,0,0,0,0
239,65cb59ff3328eca8adc58a51,TCS,EQ,N,2024-02-13,2024-02-12T18:30:00.000Z,4170.00,4081.50,4125.45,4149.50,...,None,4130.03,13-Feb-2024,NaN,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,67a9ea8015b873eaf995575c,TCS,EQ,N,2025-02-10,2025-02-09T18:30:00.000Z,4052.00,4014.35,4040.00,4036.95,...,None,4035.26,10-Feb-2025,NaN,100,0,0,0,100,0
7,67ab3c0085f54dccaefe1feb,TCS,EQ,N,2025-02-11,2025-02-10T18:30:00.000Z,4040.00,3955.00,4018.40,3963.55,...,None,3989.58,11-Feb-2025,NaN,0,0,0,0,0,0
8,67ac8d80b6348ac3a2cedb9e,TCS,EQ,N,2025-02-12,2025-02-11T18:30:00.000Z,4021.75,3940.15,3971.10,3950.15,...,None,3978.32,12-Feb-2025,NaN,0,0,0,0,0,0
9,67addf0066a44f12b734c888,TCS,EQ,N,2025-02-13,2025-02-12T18:30:00.000Z,3984.45,3902.25,3968.00,3910.15,...,None,3930.80,13-Feb-2025,NaN,0,0,0,0,0,0
10,67af30808e0d781dcf0334ad,TCS,EQ,N,2025-02-14,2025-02-13T18:30:00.000Z,3948.00,3900.00,3925.00,3934.85,...,None,3921.57,14-Feb-2025,NaN,0,0,0,0,100,0

In [9]:
pattern_counts = hcl[['DOJI', 'Engulfing', 'HAMMER', 
                      'HARAMI', 
                      'MORNINGSTAR']].apply(lambda x: (x != 0).sum())

print(pattern_counts)

DOJI           40
Engulfing      28
HAMMER          3
HARAMI         25
MORNINGSTAR     0
dtype: int64

In [10]:
hcl['Engulfing'].unique()

array([   0, -100,  100,  -80,   80], dtype=int32)

In [11]:
hcl.loc[hcl['Engulfing']!=0]

,_id,CH_SYMBOL,CH_SERIES,CH_MARKET_TYPE,CH_TIMESTAMP,TIMESTAMP,CH_TRADE_HIGH_PRICE,CH_TRADE_LOW_PRICE,CH_OPENING_PRICE,CH_CLOSING_PRICE,...,SLBMH_TOT_VAL,VWAP,mTIMESTAMP,CA,DOJI,Engulfing,HAMMER,HANGINGMAN,HARAMI,MORNINGSTAR
243,65b8e4ff11b384b5b95b0c21,HCLTECH,EQ,N,2024-01-30,2024-01-29T18:30:00.000Z,1592.45,1555.00,1580.00,1559.30,...,None,1575.56,30-Jan-2024,NaN,0,-100,0,0,0,0
216,65e85b003d619fdb6b8a2722,HCLTECH,EQ,N,2024-03-06,2024-03-05T18:30:00.000Z,1650.00,1603.85,1613.00,1644.20,...,None,1627.97,06-Mar-2024,NaN,0,100,0,0,0,0
229,66040cd89f25a30f219d43ec,HCLTECH,EQ,N,2024-03-27,2024-03-26T18:30:00.000Z,1576.85,1540.00,1569.00,1546.20,...,None,1561.15,27-Mar-2024,NaN,0,-100,0,0,0,0
232,660bf381f7e1ee6c9dc36879,HCLTECH,EQ,N,2024-04-02,2024-04-01T18:30:00.000Z,1565.00,1525.10,1559.00,1528.30,...,None,1540.21,02-Apr-2024,NaN,0,-100,0,0,0,0
236,6613dc80a9889c42a71712de,HCLTECH,EQ,N,2024-04-08,2024-04-07T18:30:00.000Z,1554.00,1537.65,1554.00,1540.05,...,None,1544.56,08-Apr-2024,NaN,0,-100,0,0,0,0
238,66167f7fe8b5eef20dd1f30b,HCLTECH,EQ,N,2024-04-10,2024-04-09T18:30:00.000Z,1552.15,1536.20,1541.05,1539.15,...,None,1542.94,10-Apr-2024,NaN,100,-100,0,0,0,0
196,662b975ee28b7d921598c21f,HCLTECH,EQ,N,2024-04-26,2024-04-25T18:30:00.000Z,1531.45,1464.95,1516.85,1473.85,...,None,1495.58,26-Apr-2024,NaN,0,-100,0,0,0,0
200,6634d2014d890ecb33500aab,HCLTECH,EQ,N,2024-05-03,2024-05-02T18:30:00.000Z,1370.00,1333.55,1370.00,1348.05,...,None,1348.33,03-May-2024,NaN,0,-100,0,0,0,0
208,6644a3e35a7728d3162ca6d1,HCLTECH,EQ,N,2024-05-15,2024-05-14T18:30:00.000Z,1340.30,1318.25,1319.25,1332.90,...,None,1332.16,15-May-2024,NaN,0,100,0,0,0,0
210,664746e247c43e58a02dd12d,HCLTECH,EQ,N,2024-05-17,2024-05-16T18:30:00.000Z,1351.00,1330.20,1351.00,1333.20,...,None,1339.47,17-May-2024,NaN,0,-100,0,0,0,0
162,66508183b31262c71f927130,HCLTECH,EQ,N,2024-05-24,2024-05-23T18:30:00.000Z,1360.00,1340.85,1360.00,1345.20,...,None,1349.46,24-May-2024,NaN,0,-100,0,0,0,0
165,6657190317d3a16202698a30,HCLTECH,EQ,N,2024-05-29,2024-05-28T18:30:00.000Z,1366.60,1346.95,1366.00,1353.10,...,None,1356.53,29-May-2024,NaN,0,-100,0,0,0,0
185,667d54791ddb15b366b578be,HCLTECH,EQ,N,2024-06-27,2024-06-26T18:30:00.000Z,1460.55,1423.50,1435.00,1454.90,...,None,1442.53,27-Jun-2024,NaN,0,100,0,0,0,0
145,669f9b8106d947166d35d1cb,HCLTECH,EQ,N,2024-07-23,2024-07-22T18:30:00.000Z,1600.80,1551.10,1574.00,1598.35,...,None,1581.04,23-Jul-2024,"[{'symbol': 'HCLTECH', 'series': 'EQ', 'ind': ...",0,100,0,0,0,0
104,66bb4b0043944ad5f60bc96c,HCLTECH,EQ,N,2024-08-13,2024-08-12T18:30:00.000Z,1608.40,1577.65,1578.00,1592.65,...,None,1594.35,13-Aug-2024,NaN,0,100,0,0,0,0
78,66f2a9e3fb85fc5d3621b29f,HCLTECH,EQ,N,2024-09-24,2024-09-23T18:30:00.000Z,1783.50,1738.35,1750.00,1775.60,...,None,1763.55,24-Sep-2024,NaN,0,100,0,0,0,0
83,66fc00de96001531001f50d0,HCLTECH,EQ,N,2024-10-01,2024-09-30T18:30:00.000Z,1822.45,1790.00,1790.00,1816.50,...,None,1804.79,01-Oct-2024,NaN,0,100,0,0,0,0
87,67051ee0e585360bdf0b6a13,HCLTECH,EQ,N,2024-10-08,2024-10-07T18:30:00.000Z,1794.00,1743.00,1774.00,1789.45,...,None,1773.74,08-Oct-2024,NaN,0,100,0,0,0,0
90,670913655b07060aa20410ab,HCLTECH,EQ,N,2024-10-11,2024-10-10T18:30:00.000Z,1852.80,1800.65,1804.00,1839.65,...,None,1834.51,11-Oct-2024,NaN,0,100,0,0,0,0
98,6719035c2bfd5a3822f85f58,HCLTECH,EQ,N,2024-10-23,2024-10-22T18:30:00.000Z,1865.00,1793.50,1793.50,1845.75,...,None,1844.93,23-Oct-2024,NaN,0,100,0,0,0,0
101,671f89dee5651d531a11ac5e,HCLTECH,EQ,N,2024-10-28,2024-10-27T18:30:00.000Z,1876.80,1845.10,1845.10,1871.75,...,None,1864.88,28-Oct-2024,NaN,0,100,0,0,0,0
32,67728b81fcbe9f5d89696fe4,HCLTECH,EQ,N,2024-12-30,2024-12-29T18:30:00.000Z,1968.95,1865.65,1888.00,1928.95,...,None,1921.33,30-Dec-2024,NaN,0,100,0,0,0,0
34,67754b94d3205bf7e5c3399b,HCLTECH,EQ,N,2025-01-01,2024-12-31T18:30:00.000Z,1936.95,1907.90,1917.40,1911.95,...,None,1918.88,01-Jan-2025,NaN,0,-80,0,0,0,0
35,6776800099c47fa1f1710d6f,HCLTECH,EQ,N,2025-01-02,2025-01-01T18:30:00.000Z,1976.30,1910.05,1911.95,1972.20,...,None,1956.30,02-Jan-2025,NaN,0,80,0,0,0,0
38,677d1780defc1db3443cdd7a,HCLTECH,EQ,N,2025-01-07,2025-01-06T18:30:00.000Z,1981.00,1908.90,1960.00,1915.90,...,None,1930.16,07-Jan-2025,NaN,0,-100,0,0,0,0
11,679cbb81e74dad1cfe69c497,HCLTECH,EQ,N,2025-01-31,2025-01-30T18:30:00.000Z,1738.20,1709.05,1709.05,1725.45,...,None,1724.09,31-Jan-2025,NaN,0,100,0,0,0,0
12,679e0d00f197463ec467bb8e,HCLTECH,EQ,N,2025-02-01,2025-01-31T18:30:00.000Z,1731.95,1688.00,1726.00,1694.00,...,None,1704.35,01-Feb-2025,NaN,0,-100,0,0,0,0
17,67a5f6009f0acd251c740564,HCLTECH,EQ,N,2025-02-07,2025-02-06T18:30:00.000Z,1731.00,1700.65,1723.15,1725.65,...,None,1720.82,07-Feb-2025,NaN,100,100,0,0,0,0

In [5]:
start_date = "22-01-2024"
end_date ="21-01-2025"
nse.index_history("NIFTY 50", start_date, end_date)

KeyError: 'd'