In [5]:
import nsepython as nse
from datetime import datetime, timedelta

In [39]:
Underlying = "NIFTY"
Index = "NIFTY 50"
Today = datetime.now().strftime("%d-%m-%Y")
OneYearAgo = (datetime.now()-timedelta(days=365)).strftime("%d-%m-%Y")
Today_mmm = datetime.now().strftime("%d-%b-%Y")
OneYearAgo_mmm = (datetime.now()-timedelta(days=365)).strftime("%d-%b-%Y")

In [40]:
Today,OneYearAgo

('23-01-2025', '24-01-2024')

In [43]:
expiry_dates = nse.expiry_history(Underlying, OneYearAgo, Today)

In [42]:
nse.nse_get_index_list()

['NIFTY 50',
 'NIFTY NEXT 50',
 'NIFTY IT',
 'NIFTY BANK',
 'INDIA VIX',
 'NIFTY 100',
 'NIFTY 500',
 'NIFTY MIDCAP 100',
 'NIFTY MIDCAP 50',
 'NIFTY INFRA',
 'NIFTY REALTY',
 'BHARATBOND-APR30',
 'NIFTY FMCG',
 'NIFTY GS 8 13YR',
 'NIFTY IND DIGITAL',
 'NIFTY MICROCAP250',
 'NIFTY MOBILITY',
 'NIFTY MS IT TELCM',
 'NIFTY NEW CONSUMP',
 'NIFTY PSE',
 'NIFTY TRANS LOGIS',
 'NIFTY100 LOWVOL30',
 'NIFTY200 VALUE 30',
 'NIFTY50 VALUE 20',
 'NIFTY500 EW',
 'NIFTY ALPHALOWVOL',
 'NIFTY ENERGY',
 'NIFTY IND TOURISM',
 'NIFTY M150 QLTY50',
 'NIFTY MIDCAP 150',
 'NIFTY MS FIN SERV',
 'NIFTY NONCYC CONS',
 'NIFTY PSU BANK',
 'NIFTY SML250 Q50',
 'NIFTY SMALLCAP 250',
 'NIFTY TOP 10 EW',
 'NIFTY100 ENH ESG',
 'NIFTY50 PR 2X LEV',
 'NIFTY50 TR 1X INV',
 'NIFTY 200',
 'NIFTY AQL 30',
 'NIFTY COREHOUSING',
 'NIFTY CORP MAATR',
 'NIFTY MID LIQ 15',
 'NIFTY PVT BANK',
 'NIFTY SERV SECTOR',
 'NIFTY SHARIAH 25',
 'NIFTY100 ESG',
 'NIFTY100 LIQ 15',
 'NIFTY100ESGSECLDR',
 'NIFTY500MOMENTM50',
 'BHARATBOND-APR31',
 'NIFTY AUTO',
 'NIFTY CONSUMPTION',
 'NIFTY EV',
 'NIFTY FINSEREXBNK',
 'NIFTY GS 10YR CLN',
 'NIFTY GS 11 15YR',
 'NIFTY GS COMPSITE',
 'NIFTY HIGHBETA 50',
 'NIFTY IND DEFENCE',
 'NIFTY INDIA MFG',
 'NIFTY LOW VOL 50',
 'NIFTY METAL',
 'NIFTY MS IND CONS',
 'NIFTY MULTI INFRA',
 'NIFTY MULTI MFG',
 'NIFTY QLTY LV 30',
 'NIFTY SMALLCAP 50',
 'NIFTY TOP 20 EW',
 'NIFTY200 ALPHA 30',
 'NIFTY50 TR 2X LEV',
 'NIFTY500 VALUE 50',
 'BHARATBOND-APR33',
 'NIFTY ALPHA 50',
 'NIFTY AQLV 30',
 'NIFTY COMMODITIES',
 'NIFTY DIV OPPS 50',
 'NIFTY FINSRV25 50',
 'NIFTY GROWSECT 15',
 'NIFTY HEALTHCARE',
 'NIFTY MID SELECT',
 'NIFTY OIL AND GAS',
 'NIFTY500 SHARIAH',
 'NIFTYMS400 MQ 100',
 'BHARATBOND-APR32',
 'INDEX1 NSETEST',
 'INDEX2 NSETEST',
 'NIFTY CAPITAL MKT',
 'NIFTY GS 10YR',
 'NIFTY GS 15YRPLUS',
 'NIFTY MEDIA',
 'NIFTY MULTI MQ 50',
 'NIFTY RURAL',
 'NIFTY100 ALPHA 30',
 'NIFTY50 DIV POINT',
 'BHARATBOND-APR25',
 'NIFTY CONSR DURBL',
 'NIFTY CPSE',
 'NIFTY FIN SERVICE',
 'NIFTY GS 4 8YR',
 'NIFTY IPO',
 'NIFTY MIDSMALLCAP 400',
 'NIFTY MIDSML HLTH',
 'NIFTY MNC',
 'NIFTY SMLCAP 100',
 'NIFTY INDIA CORPORATE GROUP INDEX - TATA GROUP 25 CAP',
 'NIFTY TOP 15 EW',
 'NIFTY200 QUALTY30',
 'NIFTY50 PR 1X INV',
 'NIFTY500 LMS EQL',
 'NIFTYSML250MQ 100',
 'NIFTY HOUSING',
 'NIFTY LARGEMID250',
 'NIFTY PHARMA',
 'NIFTY TOTAL MKT',
 'NIFTY100 EQL WGT',
 'NIFTY100 QUALTY30',
 'NIFTY200 MOMENTM30',
 'NIFTY50 EQL WGT',
 'NIFTY50 SHARIAH',
 'NIFTY500 MULTICAP',
 'Nifty Midcap150 Momentum 50',
 'NIFTY INDIA CORPORATE GROUP INDEX - MAHINDRA GROUP',
 'NIFTY INDIA CORPORATE GROUP INDEX - ADITYA BIRLA GROUP',
 'NIFTY INDIA CORPORATE GROUP INDEX - TATA GROUP',
 'NIFTY SME EMERGE',
 'NIFTY REITS & INVITS',
 'NIFTY INDIA RAILWAYS PSU',
 'NIFTY 50 FUTURES INDEX',
 'NIFTY 50 ARBITRAGE',
 'NIFTY500 QUALITY 50',
 'NIFTY500 LOW VOLATILITY 50',
 'NIFTY50 USD',
 'NIFTY 1D RATE INDEX',
 'NIFTY BHARAT BOND INDEX - APRIL 2030',
 'NIFTY SDL SEP 2025 INDEX',
 'NIFTY SDL DEC 2028 INDEX',
 'NIFTY SDL PLUS AAA PSU BOND JUL 2028 60:40 INDEX',
 'NIFTY AAA PSU BOND PLUS SDL APR 2026 50:50 INDEX',
 'NIFTY AAA PSU BOND PLUS SDL SEP 2026 50:50 INDEX',
 'NIFTY SDL PLUS AAA PSU BOND JUL 2033 60:40 INDEX',
 'NIFTY SDL PLUS G-SEC JUN 2028 70:30 INDEX',
 'NIFTY SDL SEP 2026 INDEX',
 'NIFTY BHARAT BOND INDEX - APRIL 2033',
 'NIFTY SDL SEP 2026 V1 INDEX',
 'NIFTY SDL JUL 2026 INDEX',
 'NIFTY SDL DEC 2026 INDEX',
 'NIFTY SDL PLUS G-SEC SEP 2027 50:50 INDEX',
 'NIFTY SDL PLUS AAA PSU BOND APR 2026 75:25 INDEX',
 'NIFTY SDL PLUS G-SEC JUN 2029 70:30 INDEX',
 'NIFTY SDL JUL 2033 INDEX',
 'NIFTY SDL OCT 2026 INDEX',
 'NIFTY 10 YEAR SDL INDEX',
 'NIFTY SDL PLUS AAA PSU BOND APR 2028 75:25 INDEX',
 'NIFTY SDL PLUS G-SEC JUNE 2027 40:60 INDEX',
 'NIFTY SDL JUL 2028 INDEX',
 'NIFTY SDL JUNE 2028 INDEX',
 'NIFTY 3 YEAR SDL INDEX',
 'NIFTY 5 YEAR SDL INDEX',
 'NIFTY AAA BOND JUN 2025 HTM INDEX',
 'NIFTY 5YR BENCHMARK G-SEC INDEX',
 'NIFTY INDIA GOVERNMENT FULLY ACCESSIBLE ROUTE (FAR) SELECT 7 BONDS INDEX (INR)',
 'NIFTY INDIA GOVERNMENT FULLY ACCESSIBLE ROUTE (FAR) SELECT 7 BONDS INDEX (USD)',
 'NIFTY G-SEC JUN 2027 INDEX',
 'NIFTY G-SEC DEC 2030 INDEX',
 'NIFTY G-SEC DEC 2026 INDEX',
 'NIFTY G-SEC JUL 2031 INDEX',
 'NIFTY G-SEC SEP 2027 INDEX',
 'NIFTY G-SEC JUN 2036 INDEX',
 'NIFTY G-SEC SEP 2032 INDEX',
 'NIFTY G-SEC DEC 2029 INDEX',
 'NIFTY G-SEC OCT 2028 INDEX',
 'NIFTY G-SEC APR 2029 INDEX',
 'NIFTY G-SEC MAY 2029 INDEX',
 'NIFTY INDIA SOVEREIGN GREEN BOND JAN 2033 INDEX',
 'NIFTY INDIA SOVEREIGN GREEN BOND JAN 2028 INDEX',
 'NIFTY G-SEC JUL 2027 INDEX',
 'NIFTY G-SEC JUL 2033 INDEX',
 'NIFTY BHARAT BOND INDEX - APRIL 2025',
 'NIFTY BHARAT BOND INDEX - APRIL 2031',
 'NIFTY PSU BOND PLUS SDL APR 2026 50:50 INDEX',
 'NIFTY SDL APR 2026 TOP 20 EQUAL WEIGHT INDEX',
 'NIFTY AAA BOND PLUS SDL APR 2026 50:50 INDEX',
 'NIFTY SDL PLUS PSU BOND SEP 2026 60:40 INDEX',
 'NIFTY PSU BOND PLUS SDL SEP 2027 40:60 INDEX',
 'NIFTY PSU BOND PLUS SDL APR 2027 50:50 INDEX',
 'NIFTY AAA BOND PLUS SDL APR 2026 70:30 INDEX',
 'NIFTY AAA BOND PLUS SDL APR 2031 70:30 INDEX',
 'NIFTY BHARAT BOND INDEX - APRIL 2032',
 'NIFTY CPSE BOND PLUS SDL SEP 2026 50:50 INDEX',
 'NIFTY SDL APR 2027 INDEX',
 'NIFTY SDL APR 2027 TOP 12 EQUAL WEIGHT INDEX',
 'NIFTY SDL APR 2032 TOP 12 EQUAL WEIGHT INDEX',
 'NIFTY SDL PLUS G-SEC JUN 2028 30:70 INDEX',
 'NIFTY SDL PLUS AAA PSU BOND DEC 2027 60:40 INDEX',
 'NIFTY SDL JUN 2027 INDEX',
 'NIFTY SDL SEP 2027 INDEX',
 'NIFTY AAA CPSE BOND PLUS SDL APR 2027 60:40 INDEX',
 'NIFTY AQLV 30 PLUS 5YR G-SEC 70:30 INDEX',
 'NIFTY MULTI ASSET - EQUITY : DEBT : ARBITRAGE : REITS/INVITS (50:20:20:10) INDEX',
 'NIFTY MULTI ASSET - EQUITY : ARBITRAGE : REITS/INVITS (50:40:10) INDEX']

In [44]:
nse.index_history("NIFTY 50", OneYearAgo_mmm, Today_mmm)

,RequestNumber,Index Name,INDEX_NAME,HistoricalDate,OPEN,HIGH,LOW,CLOSE
0,His63873263708263910900,,Nifty 50,23 Jan 2025,23128.3,23270.8,23090.65,23205.35
1,His63873263708263910900,,Nifty 50,22 Jan 2025,23099.15,23169.55,22981.3,23155.35
2,His63873263708263910900,,Nifty 50,21 Jan 2025,23421.65,23426.3,22976.85,23024.65
3,His63873263708263910900,,Nifty 50,20 Jan 2025,23290.4,23391.1,23170.65,23344.75
4,His63873263708263910900,,Nifty 50,17 Jan 2025,23277.1,23292.1,23100.35,23203.20
...,...,...,...,...,...,...,...,...
244,His63873263708263910900,,Nifty 50,31 Jan 2024,21487.25,21741.35,21448.85,21725.70
245,His63873263708263910900,,Nifty 50,30 Jan 2024,21775.75,21813.05,21501.80,21522.10
246,His63873263708263910900,,Nifty 50,29 Jan 2024,21433.10,21763.25,21429.60,21737.60
247,His63873263708263910900,,Nifty 50,25 Jan 2024,21454.60,21459.00,21247.05,21352.60
248,His63873263708263910900,,Nifty 50,24 Jan 2024,21185.25,21482.35,21137.20,21453.95